name: linux ldc build
on: [push, pull_request]

jobs:
  linux-build:
    name: linux ldc build
    strategy:
      matrix:
        os: [ubuntu-latest]
        dc: [ldc-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Install htslib deps
        run: |
            sudo apt-get update && sudo apt-get install -y build-essential autoconf zlib1g-dev libbz2-dev liblzma-dev libcurl4-openssl-dev libssl-dev
      - name: Get htslib version
        id: get-htslib-version
        run: |
            grep "+htslib" dub.json | sed -E 's/^.*+htslib-([0-9.]+)"/\1/g' > htslib_version.txt
            echo "::set-output name=htslib_version::$(cat htslib_version.txt)"

      - name: Cache htslib
        id: cache-htslib
        uses: actions/cache@v2
        with:
          path: htslib-${{ steps.get-htslib-version.outputs.htslib_version }}
          key: ${{ runner.os}}-htslib-${{ steps.get-htslib-version.outputs.htslib_version }}

      - name: Build htslib
        if: steps.cache-htslib.outputs.cache-hit != 'true'
        run: |
            wget https://github.com/samtools/htslib/releases/download/${{ steps.get-htslib-version.outputs.htslib_version }}/htslib-${{ steps.get-htslib-version.outputs.htslib_version }}.tar.bz2
            tar -xf htslib-${{ steps.get-htslib-version.outputs.htslib_version }}.tar.bz2
            cd htslib-${{ steps.get-htslib-version.outputs.htslib_version }}
            ./configure
            make

      - name: Install htslib
        run: |
            cd htslib-${{ steps.get-htslib-version.outputs.htslib_version }}
            sudo make install
            sudo ldconfig

      - name: Install parasail
        run: |
            wget https://github.com/jeffdaily/parasail/releases/download/v2.4.3/parasail-2.4.3-manylinux1_x86_64.tar.gz
            tar -xf parasail-2.4.3-manylinux1_x86_64.tar.gz
            cd parasail-2.4.3-manylinux1_x86_64/lib
            sudo cp -r * /usr/local/lib

      - name: build
        run: dub build
        env:
          LIBRARY_PATH: /usr/local/lib